apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: frontend-route
  namespace: default
spec:
  destination:
    name: frontend
  route:
  - labels:
      version: prod
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: middleware-route
  namespace: default
spec:
  destination:
    name: middleware
  route:
  - labels:
      version: prod
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: backend-route
  namespace: default
spec:
  destination:
    name: backend
  route:
  - labels:
      version: prod